# SPDX-FileCopyrightText: The vmnet-broker authors
# SPDX-License-Identifier: Apache-2.0

words = [
    "bootout",
    "cgo",
    "cidata",
    "cloudimg",
    "exitcode",
    "hvc",
    "rootfs",
    "strerror",
    "vmnet",
    "vmnetbroker",
    "xpc",
]
